### PR TITLE
Migration history feature

### LINKED ISSUE #233: Implement component level error handling for failed fetch

### PR DESCRIPTION
**Pull request by ibolton336**
Adds expandable migration history table to data list view

Closes #213 
Closes #233

### CODE REVIEW

**Comment by andyvesel** [comment]
Seems like this PR is a wip yet. I'd suggest to use a wip label for it

**Comment by ibolton336** [comment]
> Seems like this PR is a wip yet. I'd suggest to use a wip label for it

Ah maybe my commit messages fooled you @andyvesel . Just squashed the commit messages. 

> Seems like this PR is a wip yet. I'd suggest to use a wip label for it

Do you have any specific feedback about the code that needs to be changed?  Maybe my commit messages were misleading @andyvesel . Just squashed the commit messages.

**Comment by andyvesel** [comment]
@ibolton336 yeah, thanks for squashing it. Not a big deal but this makes a PR much easier to review (as well as adding a proper description for it) and keep small things nicer.

**Comment by ibolton336** [comment]
Ready for review @fusor/migration-engineering

**Comment by eriknelson** [comment]
@andyvesel I actually would prefer not to squash PRs because it actually makes review more difficult. It's good to see the changes as their applied, in addition to commits that *only* contain requested changes as a reviewer. If you want to see the totality of the suggested change, click on the `Files Changed` tab, and that will give you a "squashed" view.

**Pull request merged**
