### PR TITLE
Feature: add dynamic tooltip for add plan button

### LINKED ISSUE #357: Add a tooltip to `Add plan` button
This issues requires some UX discussion. We need somehow to show user why `Add plan` button is greyed out by default.

### PR DESCRIPTION
**Pull request by ibolton336**
Creates a tooltip that displays text describing why the add button is disabled. 

Closes #357

### CODE REVIEW

**Comment by ibolton336** [comment]
image

**Comment by ibolton336** [comment]
image

**Comment by eriknelson** [comment]
@vconzola how's this look to you?

**Comment by vconzola** [comment]
@eriknelson Looks good to me.

**Pull request merged**
