### PR TITLE
Add Title to Card component

### PR DESCRIPTION
**Pull request by andyvesel**
Added Title to Card component

### CODE REVIEW

**Comment by ibolton336** [comment]
Do we want to deviate from the mockups here? 
Screen Shot 2019-03-27 at 12 36 39 PM

**Comment by ibolton336** [comment]
Screen Shot 2019-03-27 at 12 38 05 PM

**Comment by andyvesel** [comment]
@ibolton336 @eriknelson could you review?

**Comment by eriknelson** [comment]
@ibolton336 Ah, I didn't realize those were actually in the mocks. It doesn't feel correct to have that wrap; looks broken to me. Let's bring this up during the call with Vince this afternoon.

**Comment by eriknelson** [comment]
@andyvesel can you rebase, I think we're going to merge this in as it is, since I pinged Vince and he's investigating further.

**Comment by eriknelson** [comment]
@andyvesel something happened to this because master kept getting merged into your branch, I'm assuming from the github button. We should try and avoid that, and you should do an actual rebase with `git rebase master` to catch up your code. Can you update your branch to be the final code you want to merge? I think what's missing is this line from your first commit:

https://github.com/fusor/mig-ui/pull/34/commits/43ae62532d4f43da913466094aa0bac7adb6639b#diff-ace5d4b63181d9d37f45862f313e0419R41

**Comment by eriknelson** [comment]
Merging this because it's actually in line with the mocks, and we're revisiting with Vince next week.

**Pull request merged**
