### PR TITLE
refactor(migration-table): update table layout and css

### PR DESCRIPTION
**Pull request by mattnolting**

### CODE REVIEW

**Comment by eriknelson** [comment]
Seeing some corrupt UI with this change:

image

**Comment by ibolton336** [comment]
@mattnolting Any idea what is causing the odd styling at the bottom of the expanded migrations table ?

**Comment by mattnolting** [comment]
Page background is set to #151515. It's a remnant of the dark theme. Included an update to page background color. 

Issue: https://github.com/patternfly/patternfly-next/issues/2240

**Comment by eriknelson** [comment]
Thanks Matt!

**Pull request merged**
